### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by vinters768** [ashiqdey/precompiled-mqtt#1]
Does this package support typescript?

**Comment by ashiqdey** [comment]
> Does this package support typescript?

Haven't checked with typescript.

**Comment by devatrox** [comment]
@vinters768 You can mock typings by creating a file called `precompiled-mqtt.d.ts` in your src folder with this content:

```ts
import MQTT from "mqtt/types";

declare module "precompiled-mqtt" {
  export default MQTT;
}
```

You need to install the "mqtt" as well

**Comment by rhiadj** [comment]
Another option is you can add `mqtt` as a dev dependency:
```
npm install mqtt --save-dev
```

... or if you're using yarn:
```
yarn add -D mqtt
```

... and add the following to your `tsconfig` to map the types from the `mqtt` dev dependency while aliasing the `precompiled-mqtt` to `mqtt`:
```
{
  "compilerOptions": {
    "types": ["mqtt"],  <<  this...
    "paths": {
      "mqtt": ["node_modules/precompiled-mqtt"],  <<  ...and this
    }
  }
}
```

So far this seems to work well (caveat: with limited testing) and means:
- your built sources won't be bloated by `mqtt` being in the built dependencies.
- you don't need to add additional additional files in your project - it just uses standard tsconfig to do the types/alias mapping

It's not better than other approaches but just another way to make types work with this module.

Hope that helps!

**Comment by tranhieu99** [comment]
create .d.ts file then put this
```
declare module "precompiled-mqtt" {
  import MQTT from "mqtt/types";
  export default MQTT;
}

```

**Comment by ashiqdey** [comment]
Typescript support had been added from version 4.3.14-beta
