### ISSUE TITLE
Not an issue.

### ISSUE THREAD

**Issue by elzii** [ashiqdey/precompiled-mqtt#10]
You're the man is all. And shame on CRA for shipping webpack@5 without providing polyfill methods. Smh.

**Comment by ashiqdey** [comment]
@elzii  Let me know if this solved your issue?

**Comment by elzii** [comment]
Completed did. At a Fortune 500 company. Before a huge demo. CI decided to grab WP@5 since the lockfile got ignored and everything caught on fire. we fixed it by polyfilling the crap out of it with

```
buffer
process/browser
util
url
os-browserify
path-browserify
crypto-browserify
````

but it was a PITA and had mixed results across x86 and aaarch64, and node versions. 

ours solution essentially was : lets get everyone on node@18 LTS, use this. ezpz. i internally publisheed my polyfil but you did it for the masses. great work.

and again Meta/React team - wtf? make the first prompt of CRA to use wp 4 (what you're used to....) or (5, but has some breaking bleeding edge changes...). What a fumble.
