### ISSUE TITLE
react-native TCP connection failing. 

### ISSUE THREAD

**Issue by snyoon** [ashiqdey/precompiled-mqtt#2]
Hello I was working on connecting to an MQTT broker on a react native application and having issues with connecting to a TCP broker but no issues connecting to a websocket one. 

Has anyone gotten more success?

**Comment by ashiqdey** [comment]
> working on connecting to an MQTT broker on a react native application and having issues with connecting to a

Which port and protocol are you using?

**Comment by snyoon** [comment]
I am able to connect to mqtt://test.mosquitto.org:8080 but not mqtt://test.mosquitto.org:1883

**Comment by ashiqdey** [comment]
> I am able to connect to mqtt://test.mosquitto.org:8080 but not mqtt://test.mosquitto.org:1883

Your client doesn't support direct mqtt protocol, you will have to use it over web socket. (8080, 8081, 8090, 8091)
