### ISSUE TITLE
connect with opitons not taking any action.

### ISSUE THREAD

**Issue by yususs** [ashiqdey/precompiled-mqtt#4]
Hi. Thanks for the module.

It doesn't show any action when I try to connect as below. Also no any error, or warning.

```
const host = 'ws://10.150.230.2:8084'

const options = {
  clientId: 'client',
  username: Auth.getUser().email.substring(0, Auth.getUser().email.lastIndexOf("@")),
  password: 'somepass',
  reschedulePings: false,
  protocolId: 'MQTT',
  protocolVersion: 4,
  clean: true,
  reconnectPeriod: 5000,
  connectTimeout: 10 * 1000,
  rejectUnauthorized: true ,
  keepalive: 10
}

socket = mqtt.connect(host, options)
```

**Comment by ashiqdey** [comment]
> Hi. Thanks for the module.
> 
> It doesn't show any action when I try to connect as below. Also no any error, or warning.
> 
> ```
> const host = 'ws://10.150.230.2:8084'
> 
> const options = {
>   clientId: 'client',
>   username: Auth.getUser().email.substring(0, Auth.getUser().email.lastIndexOf("@")),
>   password: 'somepass',
>   reschedulePings: false,
>   protocolId: 'MQTT',
>   protocolVersion: 4,
>   clean: true,
>   reconnectPeriod: 5000,
>   connectTimeout: 10 * 1000,
>   rejectUnauthorized: true ,
>   keepalive: 10
> }
> 
> socket = mqtt.connect(host, options)
> ```

Appreciate your efforts to connect. I would suggest you to post your issue in [official mqtt github](https://github.com/mqttjs/MQTT.js/issues) As this package completely unaltered compiled version of official mqtt.js so I think the official team would be better in figuring out the issue.

Also mind you that, you will have to expose port 8084 for websocket in your backend, have you done that?

**Comment by yususs** [comment]
> Appreciate your efforts to connect. I would suggest you to post your issue in [official mqtt github](https://github.com/mqttjs/MQTT.js/issues) As this package completely unaltered compiled version of official mqtt.js so I think the official team would be better in figuring out the issue.
> 
> Also mind you that, you will have to expose port 8084 for websocket in your backend, have you done that?

Yes. The port is exposed and having no issue to connect without options. 
Thanks for your time.
